### ISSUE TITLE
logout error in powermenu.sh

### ISSUE THREAD

**Issue by RanceH** [EndeavourOS-Community-Editions/worm#2]
The logout function in .config/rofi/powermenu.sh is incorrect.

It should be:
`pkill -u $USER`

Ive attached a patch that makes the required change
[worm_rofi_powermenu_patch.txt](https://github.com/EndeavourOS-Community-Editions/worm/files/8688419/worm_rofi_powermenu_patch.txt)

**Comment by killajoe** [comment]
exactly + slock is not in the packages list causing lock screen to not work if installed from ISO.

**Comment by killajoe** [comment]
but instead of a patch you could do a pull request directly .. would be more easy to apply ;)

**Comment by killajoe** [comment]
https://github.com/EndeavourOS-Community-Editions/worm/commit/e3f73e7d27b1ab67c2bba00fba7781f06446088d
already solved the issue for not using username.
